condonsax/albums/urls.py
from django.conf.urls import url

from .views import AlbumListView

app_name = 'albums'

urlpatterns = [
    url(r'^$', AlbumListView.as_view(), name='albums'),
]

condonsax/condonsax/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from condonsax.admin import condon_admin

urlpatterns = [
    url(r'^admin/', condon_admin.urls),
    url(r'albums/', include('albums.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^hiddenalbum/', include('hiddenalbum.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

condonsax/events/urls.py
from django.conf.urls import url

from .views import EventView

app_name = 'events'

urlpatterns = [
    url(r'^$', EventView.as_view(), name='event'),
]

condonsax/home/urls.py
from django.conf.urls import url

from .views import HomePageView, AboutView, ContactView

app_name = 'home'

urlpatterns = [
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^contact/', ContactView.as_view(), name='contact'),
    url(r'^$', HomePageView.as_view(), name='index'),
]

condonsax/projects/urls.py
# Django imports
from django.conf.urls import url

# Relative imports
from .views import DetailView, IndexView, TagDetailView

app_name = 'projects'
urlpatterns = [
    # ex: /projects/pk/entry-slug-goes-here
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w\d]+)/$', DetailView.as_view(), name='detail'),
    # ex /projects/tags/pk/tag-slug-here
    url(r'tags/(?P<pk>[0-9]+)/(?P<slug>[-\w\d]+)/', TagDetailView.as_view(), name='tag_detail'),
    # ex: /projects/
    url(r'^$', IndexView.as_view(), name='projects'),
]

condonsax/templates/base.html
<!DOCTYPE html>
<html lang="en-us">
<head>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <meta property="fb:app_id" content="914092952061390"/>
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap-theme.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/home.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'home/images/favicon.png' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Playfair+Display+SC|Raleway:300,400,500,700" rel="stylesheet">
    {% block header %}
    {% endblock %}
    <title>{% block title %}Chris Condon{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand-centered" href="{% url 'home:index' %}">
                <img id="brand" alt="Chris Condon: Saxophone" src="{% static 'home/images/chris-logo.png' %}"/>
            </a>
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="true">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div> <!-- navbar-header -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home:index' %}">HOME</a></li>
                <li><a href="{% url 'home:about' %}">ABOUT</a></li>
                <li><a href="{% url 'home:contact' %}">CONTACT</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'projects:projects' %}">PROJECTS</a></li>
                <li><a href="{% url 'events:event' %}">EVENTS</a></li>
                <li><a href="{% url 'albums:albums' %}">ALBUMS</a></li>               
              </ul>
        </div>
    </div>
</nav>
{% block jumbotron %}
{% endblock %}
<main id='content'>
    {% block content %}
        You shouldn't be seeing this page.
    {% endblock %}
</main>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'home/js/bootstrap.min.js' %}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>