condonsax/condonsax/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from condonsax.admin import condon_admin

urlpatterns = [
    url(r'^admin/', condon_admin.urls),
    url(r'albums/', include('albums.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^hiddenalbum/', include('hiddenalbum.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

condonsax/home/urls.py
from django.conf.urls import url

from .views import HomePageView, AboutView, ContactView

app_name = 'home'

urlpatterns = [
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^contact/', ContactView.as_view(), name='contact'),
    url(r'^$', HomePageView.as_view(), name='index'),
]

condonsax/projects/urls.py
# Django imports
from django.conf.urls import url

# Relative imports
from .views import DetailView, IndexView, TagDetailView

app_name = 'projects'
urlpatterns = [
    # ex: /projects/pk/entry-slug-goes-here
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w\d]+)/$', DetailView.as_view(), name='detail'),
    # ex /projects/tags/pk/tag-slug-here
    url(r'tags/(?P<pk>[0-9]+)/(?P<slug>[-\w\d]+)/', TagDetailView.as_view(), name='tag_detail'),
    # ex: /projects/
    url(r'^$', IndexView.as_view(), name='projects'),
]

condonsax/projects/models.py
# Standard library imports
from datetime import timedelta

# Django imports
from django.db import models
from django.utils import timezone
from django.urls import reverse

from tinymce import HTMLField


class Project(models.Model):
    """
    Project is a class that allows a blog entry to be published about a
    completed major project. Projects can include albums, commissioned
    pieces, or important performances. Projects are to be presented in the
    style of a blog, and allow embedded images and videos when needed.
    title - Title of project
    slug - url slug
    header_image - image to display at top of screen
    pub_date - Date entry was published
    body - main text of project entry
    tags - related topics
    """

    class Meta:
        verbose_name='Project'
        verbose_name_plural='Projects'


    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField('URL slug', max_length=100, unique=True)
    header_image = models.ImageField('Header Image', upload_to='media/%Y/%m/%d', blank=True)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    body = HTMLField('Body')
    tags = models.ManyToManyField('Tag', related_name='projects', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Defines primary key and slug as components of url
        """
        args = (self.pk, self.slug)
        return reverse(self, args)

    def was_published_recently(self):
        now = timezone.now()
        return now - timedelta(days=30) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Tag(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField('URL slug', max_length=100, db_index=True)

    def get_absolute_url(self):
        """
        Defines primary key and slug as components of url
        """
        args = (self.pk, self.slug)
        return reverse(self, args)

    def __str__(self):
        return self.title

condonsax/projects/views.py
# Django imports
from django.views import generic
from django.utils import timezone

# Relative imports
from .models import Project, Tag


# Create your views here.
class IndexView(generic.ListView):
    """
    View for displaying list of projects on a home screen.
    """
    template_name = 'projects/projects.html'
    context_object_name = 'project_list'
    model = Project
    paginate_by = 6

    def get_queryset(self):
        """
        Return projects sorted by date
        """
        projects = Project.objects.distinct()
        return projects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


class DetailView(generic.DetailView):
    """
    View single project
    """
    model = Project
    template_name = 'projects/detail.html'


class TagListView(generic.ListView):
    """
    View all projects assiciated with a certain tag
    """
    model = Tag
    template_name = 'projects/tag_list.html'
    context_object_name = 'tag_list'
    paginate_by = 6
    paginate_orphans = 2

    def get_queryset(self):
        return Tag.objects.distinct()


class TagDetailView(generic.DetailView):
    model = Tag
    template_name = 'projects/tag_detail.html'
    context_object_name = 'tag'
    paginate_by = 6

condonsax/projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load static %}

{# Adds page-specific header info #}
{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'projects/projects.css' %}"/>
{% if project.header_image %}
    <style type="text/css">
        #header-image {
            background: url('{{ project.header_image.url }}') no-repeat center center;
        }
    </style>
{% else %}
    <style type="text/css">
        #header-image {
            background: url({% static 'projects/images/default_header.jpg' %}) no-repeat center center;
        }
    </style>
{% endif %}
{% endblock %}

{# Adds title to browser tab #}
{% block title %}Projects - {{ project.title }}{% endblock %}

{# This is the content of the web page, displayed below the navbar #}
{% block content %}
    {# show header at top of detail page #}
<div id='header-image'></div>
<section id='fullpage'>
    <h1>{{ project.title }}</h1>
    <hr>
    <article id='project-body'>
        {{ project.body|safe }}
    </article>

    {# displays links to lists of projects with common tags #}
    {% if project.tags %}    
        <div class="tags">
            <h3>More About:</h3>

            {% for tag in project.tags.all %}
            <a class='button' href='{% url 'projects:tag_detail' tag.pk tag.slug %}'>{{ tag.title }}</a>
            {% endfor %}
        </div>
    {% endif %}
</section>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'projects/projects.js' %}"></script>
{% endblock %}

condonsax/projects/templates/projects/projects.html
{% extends 'base.html' %}
{% load static %}

{# Adds page-specific header info #}
{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'projects/projects.css' %}"/>
{% endblock %}

{# Adds title to browser tab #}
{% block title %}Projects{% endblock %}

{# This is the content of the web page, displayed below the navbar #}
{% block content %}

<section id='list-page'>
<h1>Projects</h1>
    {% if project_list %}
    <section class='cards'>
        {% for project in project_list %}
        <!-- wrapper for card -->
            <div class="card">
                {# show project header at top of card #}
                {% if project.header_image %}
                <a href="{% url 'projects:detail' project.pk project.slug %}">
                    <img src="{{ project.header_image.url }}">
                </a>
                {# or default to default header #}
                {% else %}
                <a href="{% url 'projects:detail' project.pk project.slug %}">
                    <img class="project-card-header" src="{% static 'projects/images/default_header.jpg' %}">
                </a>
                {% endif %}
                <div class="card-text">
                    <h3>
                        <a href="{% url 'projects:detail' project.pk project.slug %}">{{ project.title }}</a>
                    </h3>
                    <hr>
                    <span class="card-date">
                        {{ project.pub_date.date }}
                    </span>
                </div>
            </div>    
        {% endfor %}
        </section>
    {% else %}
    <h1>Coming Soon</h1>
    {% endif %}
</section>
{% endblock %}

{% block scripts %}
{% endblock %}

condonsax/projects/templates/projects/tag_detail.html
{% extends 'base.html' %}
{% load static %}

{# Adds page-specific header info #}
{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'projects/projects.css' %}"/>
{% endblock %}

{# Adds title to browser tab #}
{% block title %}Projects{% endblock %}

{# This is the content of the web page, displayed below the navbar #}
{% block content %}

<section id='list-page'>
<h1>Projects Tagged: {{ tag.title }}</h1>
    {% if tag.projects %}
    <section class='cards'>
        {% for project in tag.projects.all %}
        <!-- wrapper for card -->
            <div class="card">
                {# show project header at top of card #}
                {% if project.header_image %}
                <a href="{% url 'projects:detail' project.pk project.slug %}">
                    <img src="{{ project.header_image.url }}">
                </a>
                {# or default to default header #}
                {% else %}
                <a href="{% url 'projects:detail' project.pk project.slug %}">
                    <img class="project-card-header" src="{% static 'projects/images/default_header.jpg' %}">
                </a>
                {% endif %}
                <div class="card-text">
                    <h3>
                        <a href="{% url 'projects:detail' project.pk project.slug %}">{{ project.title }}</a>
                    </h3>
                    <hr>
                    <span class="card-date">
                        {{ project.pub_date.date }}
                    </span>
                </div>
            </div>    
        {% endfor %}
        </section>
    {% else %}
    <h1>Coming Soon</h1>
    {% endif %}
</section>
{% endblock %}

{% block scripts %}
{% endblock %}