condonsax/condonsax/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from condonsax.admin import condon_admin

urlpatterns = [
    url(r'^admin/', condon_admin.urls),
    url(r'albums/', include('albums.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^hiddenalbum/', include('hiddenalbum.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

condonsax/hiddenalbum/urls.py
# Django imports
from django.conf.urls import url

# Relative imports
from .views import HiddenAlbumHomeView, HiddenAlbumDetailView

app_name = 'hiddenalbum'
urlpatterns = [
    # ex: /hiddenalbum/album-slug-goes-here
    url(r'^(?P<slug>[-\w\d]+)/$', HiddenAlbumDetailView.as_view(), name='detail'),
    # ex: /hiddenalbum
    url(r'^$', HiddenAlbumHomeView.as_view(), name='hiddenalbum'),
]

condonsax/home/urls.py
from django.conf.urls import url

from .views import HomePageView, AboutView, ContactView

app_name = 'home'

urlpatterns = [
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^contact/', ContactView.as_view(), name='contact'),
    url(r'^$', HomePageView.as_view(), name='index'),
]

condonsax/hiddenalbum/models.py
from django.db import models

from albums.models import Album

class HiddenAlbum(models.Model):
    
    album = models.ForeignKey(Album)
    slug = models.SlugField('URL slug', max_length=100, db_index=True)

    def get_absolute_url(self):
        """
        Defines primary key and slug as components of url
        """
        args = (self.slug)
        return reverse(self, args)

    def __str__(self):
        return self.album.title

condonsax/hiddenalbum/views.py
from django.views import generic

from .models import HiddenAlbum


class HiddenAlbumHomeView(generic.ListView):
    """
    Class for viewing a list of hidden albums for venues/reviewers
    """
    template_name = 'hiddenalbum/hiddenalbum.html'
    context_object_name = 'album_list'
    model = HiddenAlbum
    paginate_by = 6

    def get_queryset(self):
        """
        Return projects sorted by date
        """
        hidden_albums = HiddenAlbum.objects.distinct()
        return hidden_albums.order_by('-pk')


# Create your views here.
class HiddenAlbumDetailView(generic.DetailView):
    """
    View full tracks of a particular album
    """
    model = HiddenAlbum
    template_name = 'hiddenalbum/detail.html'

condonsax/hiddenalbum/templates/hiddenalbum/detail.html
{% extends 'base.html' %}

{% block content %}
<section id='fullpage'>
<h1>{{ hiddenalbum.album.title }}</h1>
<ol>
    {% for track in hiddenalbum.album.tracks.all %}
    <li>
        <p class='track-info'>
            <span class='title'>{{ track.title }}</span>&nbsp;&nbsp;&nbsp; 
            <span class='composer'>{{ track.composer }}</span>
        </p>
        {% if track.full_audio %}
            <audio controls>
                <source src="{{ track.full_audio.url }}" type="audio/mp3">
                Your browser does not support the audio tag.
            </audio>
        {% endif %}
    </li>
    {% endfor %}
</ol>
</section>
{% endblock %}

condonsax/hiddenalbum/templates/hiddenalbum/hiddenalbum.html
{% extends 'base.html' %}

{% block content %}
<section id='fullpage'>
    {# what displays if there is a list of hidden albums #}
    {% if album_list %}
        {# links to each hidden albums page #}
        {% for hiddenalbum in album_list %}
        <a href="{% url 'hiddenalbum:detail' hiddenalbum.slug %}">
            <h3>{{ hiddenalbum.album.title }}</h3>
        </a>        
        {% endfor %}
    {# what displays if there aren't any hidden albums #}
    {% else %}
    <h1>Coming Soon</h1>
    {% endif %}
</section>
{% endblock %}